services:
  media_server:
    container_name: simple-media-server
    image: simple-media-server:latest
    build: .
    platform: linux/amd64
    init: true
    tty: true
    volumes:
      - ./example:/data:rw
    ports:
      - "127.0.0.1:8000:8000"
